# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cea98db61e559a3e4c8e8dba8177690ef0210287a2ade7d465495cb312d3d69cf53bb82b5950e9d6e2598356586c43416dc0a628f620c3aa6139ee1b80cea115

test:
  secret_key_base: 29f2701a33f82a2980bf2eca4cb16323f15a9180e09c908eb3e782b2b66a5e53d8579891b901547411391ecdf7ee479de5f57b53b6ca14d101bdec75cde9d7e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
